### ISSUE TITLE
Algorithm fails on some inputs

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [Sahil-k1509/sum_of_palindromes#6]
Hi!

It seems that your algorithm doesn't always work. For example, with input `1100000`, I get
```
1110011
88888
1001
```
They don't sum to the right number, and even worse, the first integer is already larger than the input, and not a palindrome.

**Comment by Sahil-k1509** [comment]
Hi!
Thanks for pointing it out.
I will read the research paper again and tally with my code to see where the implementation is faulty.
Are there any other cases? (especially with numbers where no of digits is less than 7)

**Comment by RagnarGrootKoerkamp** [comment]
I'm not aware of any other cases < 10^7. But if you run the test with a few large numbers with 10 - 20 digits, I think you should be able to find some more failing inputs.

**Comment by Sahil-k1509** [comment]
> I'm not aware of any other cases < 10^7. But if you run the test with a few large numbers with 10 - 20 digits, I think you should be able to find some more failing inputs.

Yes thank you very much for bringing it to my notice. I had a few bugs in implementation. 
In algorithm 3, 4 the initial values were assigned to wrong index(0 instead of 1) which ruined the whole chain of calculations. and in six_digit_function, I was returning p1, p1, p1 instead of p1, p2, p3... They were quite silly and took me lot of time to point out. Thanks to you <3
